
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

python_script:

recorder: !include recorder.yaml
history:
influxdb: !include influxdb.yaml
modbus: !include modbus.yaml
mqtt: !include mqtt.yaml