
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

python_script:

influxdb:
  api_version: 2
  ssl: false
  host: 127.0.0.1
  port: 8086
  token: !secret influxdb-token
  bucket: home_assistant
  organization: !secret influxdb-org-id

modbus: !include modbus.yaml
